"""Initial migration

Revision ID: 8f36291fc1de
Revises: 
Create Date: 2026-08-06 18:33:53.860027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f36291fc1de'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=400), nullable=True),
    sa.Column('min_price', sa.Integer(), nullable=True),
    sa.Column('max_queue_size', sa.Integer(), nullable=True),
    sa.Column('qr_code_id', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venues_id'), 'venues', ['id'], unique=False)
    op.create_index(op.f('ix_venues_qr_code_id'), 'venues', ['qr_code_id'], unique=True)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('song_title', sa.String(length=500), nullable=False),
    sa.Column('song_artist', sa.String(length=70), nullable=True),
    sa.Column('song_provider', sa.String(length=50), nullable=True),
    sa.Column('song_duration', sa.Integer(), nullable=True),
    sa.Column('price_paid', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'PLAYED', 'SKIPPED', 'CANCELLED', name='orderstatus'), nullable=True),
    sa.Column('played_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_venue_id'), 'orders', ['venue_id'], unique=False)
    op.create_table('play_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('song_title', sa.String(length=500), nullable=True),
    sa.Column('song_artist', sa.String(length=500), nullable=True),
    sa.Column('song_provider', sa.String(length=50), nullable=True),
    sa.Column('skipped', sa.Boolean(), nullable=True),
    sa.Column('price_paid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_play_log_id'), 'play_log', ['id'], unique=False)
    op.create_index(op.f('ix_play_log_order_id'), 'play_log', ['order_id'], unique=False)
    op.create_index(op.f('ix_play_log_venue_id'), 'play_log', ['venue_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_play_log_venue_id'), table_name='play_log')
    op.drop_index(op.f('ix_play_log_order_id'), table_name='play_log')
    op.drop_index(op.f('ix_play_log_id'), table_name='play_log')
    op.drop_table('play_log')
    op.drop_index(op.f('ix_orders_venue_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_venues_qr_code_id'), table_name='venues')
    op.drop_index(op.f('ix_venues_id'), table_name='venues')
    op.drop_table('venues')
    # ### end Alembic commands ###
