"""add_expires_at_to_orders

Revision ID: e11f85401201
Revises: d30d78b61b59
Create Date: 2026-08-14 18:08:38.950065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e11f85401201'
down_revision: Union[str, Sequence[str], None] = 'd30d78b61b59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'expires_at')
    # ### end Alembic commands ###
